version: "3.9"
volumes:
  pgdata:
  static:
networks:
  backend:
    driver: bridge
services:
  web:
    build: .
    ports:
      - 8000
    volumes:
      - static:/static
    depends_on:
      - db
    env_file:
      - .env.dev
    networks:
      - backend
    restart: unless-stopped
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=201224
      - POSTGRES_DB=netology_stocks_CRUD
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netology_stocks_CRUD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - backend